### ISSUE TITLE
Support for armv5tel?

### ISSUE THREAD

**Issue by kevin-smets** [rednoah/java-installer#1]
Will you support ARM v5 at some point? I currently have a DS211 which uses a MARVELL Kirkwood 88F6282. If so, that'd be awesome!

Otherwise, it may be time for an upgrade :p.

**Comment by rednoah** [comment]
Oracle doesn't support Java SE for armv5tel arch:
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

You might be able to get Java Embedded working, but downloads are restricted to registered users, you'll have to install it manually:
http://www.oracle.com/technetwork/java/embedded/embedded-se/downloads/index.html
https://www.youtube.com/watch?v=8N6hYNj_QzY

**Comment by rednoah** [comment]
I'll just leave it as an open issue. Can't be fixed.

**Comment by kevin-smets** [comment]
Ah damn, thanks for the reply though! Time for an upgrade, I've been eyeing that DS216Play :).

**Comment by rednoah** [comment]
If you intend to run Java code, I'd make sure that it'll run with the `Linux ARM v6/v7 Hard Float ABI` or `Linux ARM v8 Hard Float ABI` build.

**Comment by rednoah** [comment]
There's Java Embedded builds that should work, but because download requires an oracle login, I can't download it automatically in the install script... :(
http://www.oracle.com/technetwork/java/embedded/embedded-se/downloads/index.html

**Comment by worldjoe** [comment]
I ended up here on a google search. Just FYI, one way another package got around this problem is documented here:
http://forum.minimserver.com/showthread.php?tid=825

Basically they prompt the user to download the files manually and drop them in a known location.

**Comment by smileyn64** [comment]
I used same trick to have filebot on my ds411slim.

Once java downloaded and installed with the pcloadletter package, install the java installer from the filebot report, it will detect the current java install and bypass the activation.

Filebot can now be installed and work.

With this trick, for some reasons I cannot launch filebot via command line as admin, must sudo.

Also, don't expect fast performance on the armv5... But it works!

**Comment by WtfJoke** [comment]
Sorry to dig this old issue out. I used latest jdk8 embedded so far. But since newest filebot update java 11 is required.

I experience the same error as this person https://www.filebot.net/forums/viewtopic.php?t=11571

Is there a way I still can run filebot @rednoah?

**Comment by rednoah** [comment]
Yes, you can use the `*-portable-jdk8.tar.xz` generic Linux / Java 8 compatibility build.

**Comment by WtfJoke** [comment]
Thanks a lot rednoah! You're awesome. I guess there is no separate .spk / package source for that (I like the automated updates)?

**Comment by rednoah** [comment]
No, I don't plan on maintaining a SPK source dedicated to 8+ year old devices. ;)
