### ISSUE TITLE
No Java Update via Packagecenter

### ISSUE THREAD

**Issue by DKeppi** [rednoah/java-installer#10]
I know there is a new Java Package 1.8.0_121, i have 1.8.0_111 installed.
There is no update shown in PackageCenter, so i removed your Server in Settings and put it in again - still no update!
Is there a fault in your https://app.filebot.net/syno/index.json?

**Comment by rednoah** [comment]
Since `index.json` looks good to me, it's probably a DSM issue.

**Comment by DKeppi** [comment]
But that is very strange because from every Package Server i get Updates (Synocommunity, cphub, ...)
And also from yours a few weeks ago (Filebot), but not for Java!

**Comment by DKeppi** [comment]
Could it be the https in the link?
For filebot.spk its only http

**Comment by rednoah** [comment]
The Synology version comparator probably can't deal with `1.8.0_111` and `1.8.0_121` because `0_111` and `0_121` are not numbers.

If you uninstall everything and refresh the cache, the DSM will definitely show `1.8.0_121` because that's the only one in the package index.

**Comment by DKeppi** [comment]
It shows me the newest Version but no Update

![image](https://cloud.githubusercontent.com/assets/2063381/23937787/88d3399c-0959-11e7-8f1b-5f02b4bd5042.png)

**Comment by DKeppi** [comment]
Ok i will install it manually...thx

**Comment by rednoah** [comment]
Yep, looks like DSM doesn't understand that `1.8.0_121` is newer than `1.8.0_111`.
