### ISSUE TITLE
Checksum Issues clean installing 1.8.0_121 on Synology (Upgrades work fine, however)

### ISSUE THREAD

**Issue by sg1888** [rednoah/java-installer#11]
I tried clean installing 1.8.0_121 on a Synology, but kept getting a SHA256 checksum error.   The install cancels after 10 seconds.

EDIT: The upgrade did not work properly.  Still having checksum issues.

**Comment by rednoah** [comment]
What does the log say?

**Comment by sg1888** [comment]
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz HTTP/1.1
> User-Agent: curl/7.36.0
> Host: download.oracle.com
> Accept: */*
> Cookie: oraclelicense=accept-securebackup-cookie
>
< HTTP/1.1 302 Moved Temporarily
< Server: AkamaiGHost
< Content-Length: 0
< Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz
< Date: Mon, 20 Mar 2017 17:29:09 GMT
< Connection: keep-alive
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
> GET /otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz HTTP/1.1
> User-Agent: curl/7.36.0
> Host: edelivery.oracle.com
> Accept: */*
> Cookie: oraclelicense=accept-securebackup-cookie
>
< HTTP/1.1 302 Moved Temporarily
< Server: Oracle-HTTP-Server-11g
< Location: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz?AuthParam=1490031069_023f7f97f921b9d6f993cdf0e8d5ecce
< Content-Type: text/plain
< Content-Language: en
< Content-Length: 531
< Date: Mon, 20 Mar 2017 17:29:09 GMT
< Connection: keep-alive
<
{ [data not shown]
100   531  100   531    0     0   1454      0 --:--:-- --:--:-- --:--:--  2577
> GET /otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz?AuthParam=1490031069_023f7f97f921b9d6f993cdf0e8d5ecce HTTP/1.1
> User-Agent: curl/7.36.0
> Host: download.oracle.com
> Accept: */*
> Cookie: oraclelicense=accept-securebackup-cookie
>
< HTTP/1.1 200 OK
< Server: Apache
< Accept-Ranges: bytes
< Content-Type: application/x-gzip
< Last-Modified: Wed, 14 Dec 2016 19:42:01 GMT
< ETag: "91972fb4e753f1b6674c2b952d974320:1482266233"
< Content-Length: 183246769
< Cache-Control: private, max-age=554
< Date: Mon, 20 Mar 2017 17:29:09 GMT
< Connection: keep-alive
<
{ [data not shown]
100  174M  100  174M    0     0  16.2M      0  0:00:10  0:00:10 --:--:-- 15.2M
egrep: unrecognized option '--only-matching'
BusyBox v1.16.1 (2015-11-12 18:00:37 CST) multi-call binary.

No help available.

Expected SHA256 checksum: 97e30203f1aef324a07c94d9d078f5d19bb6c50e638e4492722debca588210bc
Actual SHA256 checksum:
ERROR: SHA256 checksum mismatch
`

**Comment by rednoah** [comment]
Strange:
```
egrep: unrecognized option '--only-matching'
```
What version of DSM are you using?

**Comment by sg1888** [comment]
DSM 5.2-5644 Update 5 on a DS1812+

**Comment by rednoah** [comment]
OK. Dropping support for DSM 5.

https://github.com/rednoah/java-installer/commit/25e45de249ada35ba02ce769e4a92f93e9d7ecbd
