### ISSUE TITLE
SPK Server Update?

### ISSUE THREAD

**Issue by DKeppi** [rednoah/java-installer#13]
Just a question about you SPK Server...
When you think the new versions will be available here -> https://get.filebot.net/syno/
https://github.com/rednoah/java-installer/releases shows me 144 and 151 Versions

THX

**Comment by DKeppi** [comment]
Should i download it manually?

**Comment by rednoah** [comment]
It doesn't matter. Synology DSM doesn't auto-update newer versions anyway because it doesn't recognize the version string as newer.

**Comment by DKeppi** [comment]
Yes...just forgotten that, you mentioned it in #10
Installed manually

THX
