### ISSUE TITLE
Synology Package: Unofficial JAVA Installer

### ISSUE THREAD

**Issue by gericb** [rednoah/java-installer#14]
Package Source: https://get.filebot.net/syno/

Unofficial JAVA Installer actually isn't downloading the most current JAVA SE that you indicate here, 1.8.0_162-b12.  It is actually downloading and installing 1.8.0_131.  Based on your info, once the package is executed, it should be getting the newest version automatically.

**Comment by rednoah** [comment]
So you're saying the `1.8.0_131` download link still works and Java `1.8.0_131` is installed successfully?

**Comment by gericb** [comment]
Hello, thanks for the fast reply!  Just to validate my source:


[cid:7fa4290d-15ef-4f8d-957c-05c8442f8c57]

Based on the description listed for your awesome installer package, once clicked to install, it's indicated "During the install, this package will download the latest Oracle JAVA SE Dev Kit"

[cid:60283bcd-21e9-46b9-9bc8-d13d6c776220]
________________________________

As you can see, it's downloading and installing 1.8.0_131, but your GitHUB page is showing a newer version: 1.8.0_162-b12, but this version is not what is being installed with the Unofficial JAVA Installer Synology Package.

[cid:ef5725f5-6573-4bd3-8416-6d59a0a78f58]

Maybe I am misunderstanding what should be going on, with the installer...let me know, my apologies if so.

The functionality of FileBot is totally fine and working GREAT as is, but I know over time, having an outdated version of JAVA would be an issue, so I wanted to bring this up largely due to this point.

When a newer version of JAVA comes out, that you have on your GitHub page, would the Synology Package show there is an update available and just download the newer JAVA component, to keep things updated?

I looked on your GitHub page to see if there was an easy manual way to just update the JAVA version, by various ways, even downloading it from Oracle, but nothing seems to work in updating, so I have just left it on the 1.8.0_131 and contacting you.

ALSO, I want to thank you VERY VERY MUCH for your creativity and hardwork, it's amazing FileBot, and so perfectly crafted easy to install, made a HUGE difference with Plex, where nothing else has previously.

Thank You,
Greg

--------------------------

**Comment by rednoah** [comment]
I see. It's not high priority then. The package repository is updated whenever FileBot is updated, since there's no FileBot update, there's also no Java update.

However, if you really want the latest minor update, then can download the latest SPK and install manually:
https://github.com/rednoah/java-installer/releases

I'll keep this issue open until the software sources are updated. Might not be anytime soon.

**Comment by rednoah** [comment]
Done.
