### ISSUE TITLE
Installer ends successfully but with Oooops, somthing went wrong... View Log for details

### ISSUE THREAD

**Issue by taquionbcn** [rednoah/java-installer#15]
Installations ends ok with that message.

At synology logs center there aren't any errors or warning.
If I end the installation by clicking Ok, the application shows with a repair button at the package center.

Is there any other log I should search via ssh?

any other information don't hesitate me to ask.

EDIT: 
I found some logs via ssh:
/var/logs/message

> 2018-05-08T20:35:11+02:00 LEPTON synoscgi_SYNO.Core.Package.Installation_1_install[27353]: resource_api.cpp:163 Acquire service-cfg for oracle-java when 0x0001 (done)
> 2018-05-08T20:35:16+02:00 LEPTON synoscgi_SYNO.Core.Package.Installation_1_install[27353]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:16+02:00 LEPTON synoscgi_SYNO.Core.Package_1_get[27353]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:16+02:00 LEPTON synoscgi_SYNO.Core.Package_1_list[28197]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:16+02:00 LEPTON synopkg: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:17+02:00 LEPTON synoscgi_SYNO.Core.Package_1_list[29208]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:18+02:00 LEPTON synoscgi_SYNO.Core.Package.Installation_1_install[28876]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:18+02:00 LEPTON synoscgi_SYNO.Core.Package.Server_1_list[29553]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:19+02:00 LEPTON synoscgi_SYNO.Core.Package_1_list[29958]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> 2018-05-08T20:35:21+02:00 LEPTON synoscgi_SYNO.Core.Package_1_list[30604]: pkgtool.cpp:2942 Package is broken, oracle-java, [150]
> ...

thanks

**Comment by rednoah** [comment]
What does the relevant log say? Open DSM, go to Package Manager, and click `View Log` in the Java Installer package.

**Comment by DKeppi** [comment]
On my DS916+ the installation was sucessfull without any error :)

**Comment by taquionbcn** [comment]
Sorry I didn't say before,  I have  ds716+.

In order to get the logs I've installed again version 1.8.0_171 and it's running and OK.

I don't now what was happening before.

**Comment by rednoah** [comment]
I have recently updated the package, because the older one was no longer working. That's probably what fixed it.

**Comment by rednoah** [comment]
What does the log say?

```
cat /volume1/@appstore/oracle-java/install-jdk.log
```

**Comment by DesEagle1220** [comment]
Download http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
jdk-8u171-linux-x64.tar.gz: No such file or directory
Expected SHA256 checksum: b6dd2837efaaec4109b36cfbb94a774db100029f98b0d78be68c27bec0275982
Actual SHA256 checksum: 
ERROR: SHA256 checksum mismatch

**Comment by rednoah** [comment]
Looks like there's a new update, and the old download links no longer work. This will require an update.
