### ISSUE TITLE
Is a Version string change possible?

### ISSUE THREAD

**Issue by DKeppi** [rednoah/java-installer#16]
Hi rednoah!

as i mentioned in #10 and #13 the DSM Package Center did not show an Update when you release a new Package.
As you mentioned in this Issues, the reason for that is the version string that the Package Center did not recognize.
Is it possible to change the Version string from 1.8.0_xxx to 1.8.0-xxx, so future updates via Package Center will work?

THX and BR
DKeppi

**Comment by rednoah** [comment]
Yes, but these minor updates don't really make a difference. I expect the current release to be the last one, or maybe the next one, but I probably can't go past Java 8 due to supported platforms.

**Comment by rednoah** [comment]
Java 9+ changes the official versioning to something more sensible anyway. But Oracle doesn't release binaries for ARM and x86 platforms anymore, which is 100% of Synology NAS devices.

I'm not aware of anyone else who is building OpenJDK binaries for all platforms I'd need, and I don't plan on taking the job myself.

**Comment by DKeppi** [comment]
Ohhh ok :(

So hopefully someone will compile it for x86 in the future or Synology will release their own package with java 9?

Thanks for your help
