### ISSUE TITLE
SRM 1.2-7742 Update 5 RT2600ac error

### ISSUE THREAD

**Issue by ctspeck** [rednoah/java-installer#17]
Unable to install on SRM 1.2-7742 Update 5 RT2600ac
<img width="1792" alt="screenshot 2019-01-18 at 06 40 34" src="https://user-images.githubusercontent.com/37475640/51369645-4395b700-1aec-11e9-92e0-19ab6d761efb.png">
<img width="1792" alt="screenshot 2019-01-18 at 06 41 03" src="https://user-images.githubusercontent.com/37475640/51369646-4395b700-1aec-11e9-9b4e-c237fd97ae74.png">

**Comment by rednoah** [comment]
Unfortunately, I have no idea how to make an SPK package work on both "DiskStation Manager" and "Synology Router Manager" devices.

Can you login via SSH? What CPU architecture does your device have?

**Comment by rednoah** [comment]
As far as the SPK package is concerned, DSM 6 is required:

```
<info name="firmware" value="6.0" />
```

But I have no idea how that translates to SRM. Plus it seems that it's a SRM bug, since you seem to be running at least the version that it asks of you.
