### ISSUE TITLE
JAVA_HOME

### ISSUE THREAD

**Issue by DKeppi** [rednoah/java-installer#2]
Hello,

i like your package very much and it works like a charm with filebot, but is it possible to implement the JAVA_HOME Variable in /etc/profile like patters do in his spk? -> http://packages.pcloadletter.co.uk/downloads/java1.8.0_65-merged-0035.spk

With JAVA_HOME your package will also work with other services like jdownloader2 -> https://spk.netzbaer.de/JDownloader_noarch_006.spk

Thanks a lot.

**Comment by rednoah** [comment]
You can do that yourself:
```
export JAVA=/usr/local/java
```
The script will never modify `/etc/profile` but it will create a link `/usr/local/java`.

**Comment by rednoah** [comment]
I understand that tools like Apache Ant require `JAVA_HOME` but Java programs that simply call `java -jar ...` shouldn't fail simply because `JAVA_HOME` isn't set when `java` calls work perfectly fine.

**Comment by rednoah** [comment]
I've added a feature request for supporting the `/etc/profile.d/*.sh` convention, which would allow me to add this feature:
https://forum.synology.com/enu/viewtopic.php?f=3&t=107245

**Comment by DKeppi** [comment]
Thanks for all the informations and your request to support the /etc/profile.d/*.sh convention.
Hopefully it will support JAVA_HOME Variable in the future....

**Comment by rednoah** [comment]
https://github.com/rednoah/java-installer/commit/8e83335e1a2135e5f8ab0fa41e58ea4d2335b8f4
