### ISSUE TITLE
can't download java-installer

### ISSUE THREAD

**Issue by maisen20** [rednoah/java-installer#26]
Unfortunately, I cannot install the latest Java version (v2.16) via the package manager on my Synology DS1019+ (DSM 7.0-41882).

When I click to update on the Java package, I get an error message that "java-installer" could not be downloaded. 

Even after I re-added the package source https://get.filebot.net/syno/ it does not work.

**Comment by rednoah** [comment]
`https://get.filebot.net/syno/` currently lists DSM 6.2.4 packages, which aren't compatible with DSM 7:
https://www.filebot.net/linux/syno.html

If you're using the latest DSM 7 beta then you can use these alternative package sources:
https://www.filebot.net/forums/viewtopic.php?t=12412

**Comment by maisen20** [comment]
Oh sorry, I didn't see that at all. Thank you very much!🙈
