### ISSUE TITLE
Failed to update "Java Installer". This package does not contain a digital signature

### ISSUE THREAD

**Issue by koonfoon** [rednoah/java-installer#27]
My DSM firmware is 6.2.4-25556 on ds218+
I get the message stating that package does not contain "digital signature".
Please help. Thank you.

**Comment by GadgetComa** [comment]
Same message trying to install on my DS916+ with DSM 6.2.4-25556. Currently installed version of the package is 2.13. Happy to provide any additional information or do troubleshooting to help out. Thanks!

**Comment by koonfoon** [comment]
I did some digging on google. Go to Package Center -> Settings -> General. Set Trust Level to "Any Publisher". Here is one of the [link](https://help.resilio.com/hc/en-us/articles/206664850-Synology)

**Comment by rednoah** [comment]
Please read the `Notes` section for other potential issues that you will likely encounter:
https://www.filebot.net/linux/syno.html
