### ISSUE TITLE
Doesn't work on DSM 7

### ISSUE THREAD

**Issue by melgu** [rednoah/java-installer#28]
On DSM 6 the installer worked. On DSM 7 I get an error that the download failed.

Device: DS418
OS: DSM 7.0-41890

**Comment by rednoah** [comment]
1.
What does the error say exactly?

2.
https://www.filebot.net/forums/viewtopic.php?t=12412

**Comment by melgu** [comment]
1. It just said that the download failed (nothing else)
2. Works! Thanks for the quick reply 👍
