### ISSUE TITLE
Check for log4j vuln

### ISSUE THREAD

**Issue by mhombach** [rednoah/java-installer#33]
Hey,

since many systems (e.g. Synology) are using your java package here, please check the complete package for the log4j vulnerability and if found, fix it. Log4j could also be used by some lib that you are using, to I guess you need to search the whole code if log4j is used :/

Thanks in advance

**Comment by rednoah** [comment]
`java` does not include the `log4j` by default. The code in this repository is just shell script and uses `echo` to print messages to console output.

**Comment by mhombach** [comment]
Alright, thx for clarification, just wanted to make sure. I'm just not into java so I could have missed something.

**Comment by rednoah** [comment]
No worries. Although the log4j vulnerability doesn't apply to this project per se, the 3rd party applications that require `java` to run may use `log4j` as a dependency, so you could search for possibly vulnerable software along that line.

**Comment by mhombach** [comment]
Yeah. I'm using your Java package for running "JDownloader" on my Synology NAS and me and a few others already contacted them. But luckily it seems that they aren't using `log4j` :)

**Comment by DKeppi** [comment]
What about filebot?

**Comment by mhombach** [comment]
@DKeppi 
What do you mean with "filebot"? If that's some App, it won't be discussed here on this repo, because this repo is only providing the `java` runtime and has nothing to do with the apps which might be using java :)

**Comment by mhombach** [comment]
@DKeppi But this repository, where you are currently asking, is only about the `java-installer` package.
I would kindly ask you to see/create an issue in the repository of that "fileBot" app, or directly reach out to rednoah :)

**Comment by rednoah** [comment]
> What about filebot?

`filebot` does not use `log4j`.

**Comment by rednoah** [comment]
> @DKeppi But this repository, where you are currently asking, is only about the `java-installer` package. I would kindly ask you to see/create an issue in the repository of that "fileBot" app, or directly reach out to rednoah :)

It's fine. The `java-installer` package exists for the sole purpose of providing the `java` native dependencies for the `filebot` package:
https://www.filebot.net/linux/syno.html



> What do you mean with "filebot"?

That's pretty funny actually. I didn't know that this package is actually used by non-filebot users as well. Cheers. 🍻

**Comment by DKeppi** [comment]
@rednoah Thanks for the clarification!

As you say, filebot is the only reason for me to use your java binary! But if its usefull for other reasons also….congratulations 🥳

**Comment by mhombach** [comment]
@rednoah ok, that's actually really funny, you say this package was primarily developed for your own `filebot` app? :D To be honest, I'm not sure I got that package from, I guess it was in some tutorial years ago on "how to run JDownloader in Synology NAS".
@DKeppi Misunderstanding then on my side. If `filebot` and this repo are tightly linked together, then this is the right place to ask about `log4j` :)
