### ISSUE TITLE
Suggestion: Make it look like old Synology Java

### ISSUE THREAD

**Issue by colin1497** [rednoah/java-installer#35]
Since Synology doesn't install Java on DSM 7+, why not make this look more like a drop-in replacement, so that anything that was previously using the Synology Java package will more easily leverage this package?  I'm not sure what all would need to change, but it's a thought.

**Comment by rednoah** [comment]
Does it not work already? The package will add `java` to the `$PATH`, and so it'll work for any program or script that simply calls `java ...`.

**Comment by rednoah** [comment]
If the package uses the `java` executable by calling `java` or `/usr/local/bin/java` then it'll work:
```
$ ls -l `which java`
lrwxrwxrwx 1 root root 44 May 10 16:24 /usr/local/bin/java -> /var/packages/java-installer/target/bin/java
```

However, if it's hardcoded to `/var/packages/<synology java package name>/target/bin/java` then there's nothing you can do. The developer or package maintainer should use `java` so different packages can then satisfy that dependency.
