### ISSUE TITLE
Installation on Syno DS411-Slim failed

### ISSUE THREAD

**Issue by smileyn64** [rednoah/java-installer#4]
Hi,
I tried to install Java on my Sinology DS411-Slim (for Filebot usage) and it failed.
Hereunder a screenshot of the error message.
![02](https://cloud.githubusercontent.com/assets/15152952/12871893/a4ad6068-cdc1-11e5-924d-8925bfb4c895.jpg)

I then created manually a folder "java" in /usr/local/bin/
This time it failed due to permission.
![03](https://cloud.githubusercontent.com/assets/15152952/12871961/057b3314-cdc4-11e5-9413-d0dd21d8fd7c.jpg)

Chmod the folder doesn't fix the issue unfortunately.
Regards.

**Comment by rednoah** [comment]
What does the log say? Click *View Log*.

**Comment by smileyn64** [comment]
I erase the folder I created, I verified everything the packages was uninstalled and proceed to re-install.
The log says:
>Unkown CPU architecture: armv5tel

**Comment by rednoah** [comment]
`armv5tel` is not supported, and can't be supported unless Oracle publishes an official Java SE build, which it won't.

**Comment by smileyn64** [comment]
I managed to get Java 8 Embedded installed on my server.
FYI [http://minimserver.com/install-synology.html#Installing%20Java%20(ARMv5%20and%20PowerPC%20models)](url)

Filebot is working fine.
here under version extract.
![02](https://cloud.githubusercontent.com/assets/15152952/13029492/cc92d410-d2c0-11e5-99d1-f7533b9be1ab.png)

**Comment by rednoah** [comment]
Yes, as long as Oracle has a Java 8 build it should work. The Java Embedded builds for the older ARM and PPC architectures are behind a login wall, so this package can't auto-download-install them.

If you download the package manually you can always do the "install" (i.e. unpack+symlink) manually via ssh:
https://www.youtube.com/watch?v=8N6hYNj_QzY
