### ISSUE TITLE
JDK 17.0.10

### ISSUE THREAD

**Issue by panther7** [rednoah/java-installer#40]
Changelog:
* https://adoptium.net/temurin/release-notes/?version=17.0.10+7
* https://docs.bell-sw.com/liberica-jdk/17.0.10b13/general/release-notes/

**Comment by rednoah** [comment]
We'll look into updating things to `JDK 21 LTS` once the Adoptium API works again for our purposes:
https://github.com/adoptium/api.adoptium.net/issues/945

**Comment by rednoah** [comment]
We'll stick to `JDK 17 LTS` for the time being due to `JDK 21 LTS` no longer supporting `x86`.

**Comment by panther7** [comment]
Is x86 (32 bit) still live? All devices, under the age of ten, supports x86_64 or arm.

**Comment by panther7** [comment]
Btw, release folder is not modified... still "old" version.

> https://raw.githubusercontent.com/rednoah/java-installer/latest/release/get-java.sh

**Comment by rednoah** [comment]
> Is x86 (32 bit) still live? All devices, under the age of ten, supports x86_64 or arm.

Whenever we drop support for 32-bit MSI installers, someone shows up that was using them all along for some reason.

**Comment by rednoah** [comment]
> Btw, release folder is not modified... still "old" version.
> 
> > https://raw.githubusercontent.com/rednoah/java-installer/latest/release/get-java.sh

I saw nothing in the change notes that would be reason for pushing an auto-update to everyone.
