### ISSUE TITLE
Synology package is expecting a different checksum

### ISSUE THREAD

**Issue by MrCee** [rednoah/java-installer#6]
@rednoah 

The package downloaded from https://app.filebot.net/syno/ isn't completing correctly. The wrong checksum is expected.

Expected SHA256 checksum: 3beda1742719400bc493cf118fc3c71697971cec3ae95a2430a337eb4d143dda
Actual SHA256 checksum: f4f1f7ab1b5986aa2ee2a2f035a2d7a8ab57a673bdee4fc51d8127dd84f423ae
ERROR: SHA256 checksum mismatch

The first checksum relates to embedded java: **ejdk-8u73-linux-i586.tar.gz**
The second checksum relates to this version: **jdk-8u73-linux-i586.tar.gz**

Are you able to take a look?

Thanks

**Comment by MrCee** [comment]
I changed the checksum in the script to match the file downloaded. After a lengthly install list it ends with an error....

```
Execute 30s 12:52s /volume1/@appstore/oracle-java/jdk1.8.0_73/jre/bin/java -XshowSettings -version
jdk1.8.0_73/jre/plugin/
jdk1.8.0_73/jre/plugin/desktop/
jdk1.8.0_73/jre/plugin/desktop/sun_java.png
jdk1.8.0_73/jre/plugin/desktop/sun_java.desktop
jdk1.8.0_73/jre/README
jdk1.8.0_73/jre/COPYRIGHT
Execute 30s 12:52s /volume1/@appstore/oracle-java/jdk1.8.0_73/jre/bin/java -XshowSettings -version
./install-jdk.sh: line 62: 30s 12:52s /volume1/@appstore/oracle-java/jdk1.8.0_73/jre/bin/java: No such file or directory
```

**Comment by MrCee** [comment]
After looking through a few paths, I found that the symlink in `/usr/local/bin` is created incorrectly which shows `java -> 30s 12:52s /volume1/@appstore/oracle-java/jdk1.8.0_73/jre/bin/java`

**Comment by MrCee** [comment]
I'm on DSM 6.0rc...... I think I may have found a fix to why java isn't showing up in PATH on a few posts recently.. I've changed the following to include 9 fields using "cut" and removed "sed".

FROM:

JAVA_EXE=\`find "$PWD" -name "java" -type f -print0 | xargs -0 ls -Alt1 | head -n 1  | sed -e 's/\s\+/\s /g' | cut -d' ' -f7-`

TO: 

JAVA_EXE=\`find "$PWD" -name "java" -type f -print0 | xargs -0 ls -Alt1 | head -n 1  | cut -d' ' -f9-`

OUTPUT:

`/volume1/@appstore/oracle-java/jdk1.8.0_73/jre/bin/java`

**Comment by rednoah** [comment]
It works fine on my `DS213J` with `DSM 5`. I haven't tested with DSM 6 but it seems odd that a simple bash script would behave differently...

**Comment by rednoah** [comment]
Please confirm that this is working now:
https://github.com/rednoah/java-installer/blob/master/release/install-jdk.sh

**Comment by MrCee** [comment]
Thank you!
That worked perfectly, no errors during install, all symlinks are correct.
Cheers :)
