### ISSUE TITLE
Doesn't work and breaks things

### ISSUE THREAD

**Issue by remouk** [rednoah/java-installer#8]
Hi there. Thanks for the work, because an automatic java package is much needed. But this one doesn't work for me.

* I have a DS213air
* I use Java for Filebot only
* Everything worked fine with my old non-automatic java package
* When the update for Filebot arrived, it came with this unofficial java installer as a dependance
* I said OK and installed it
* But it won't launch, so Filebot won't launch

I tried a fresh install (removing Filebot, my old java stuff) : 
* Reinstalling Filebot doesn't work because unofficial java installer won't install anymore
* Installing only unofficial java installer, doesn't work either

Please, just remove this as a dependance, just like it was before, so I can install Filebot.

**Comment by rednoah** [comment]
What does **View Log** say?

**Comment by remouk** [comment]
I cannot run filebot because it's not installed, because it requires "unofficial java installer" as a dependency, and "unofficial java installer" won't install because I don't know. :/

What exactly is **View Log** ? In the Synology Log Center, there's nothing happening when I try to install your package. In the UI, the window just disapears...

Maybe I can download Filebot somewhere and not being bothered by this dependency I don't need (because I can install my own java)?

**Comment by rednoah** [comment]
Package Manager -> Oracle Java SE -> View Log

**Comment by remouk** [comment]
Thanks for the fast replies!

1.
No can do. Package is NOT installed, so there's no log. :(

2.
Yes and no. There's a dependency issue, because it should not require the "unofficial java installer" while I already have a java with the good version running. I haven't found a solution so I'll ask the support.

But the real problem is that "unofficial java installer" won't install. No error, no log, the window disappears and nothing is installed anywhere. I think I tried everything. :/

Maybe it's because my Synology is a few years old (they already shut down NodeJS, there won't be a v4 while it's mandatory for Filebot Node...). That's a shame because everything worked fine until those changes...

3) Ok I managed to find the stuff and it works. I'll leave a few informations so it can help someone having the same problem as me.

- Install java through this package: https://pcloadletter.co.uk/2011/08/23/java-package-for-synology/ (you'll have to manually download java from oracle... Yes it requires you to create an account... But it works well)
- Download the portable version of Filebot from sourceforge. Make a link (ln -s) for the filebot.sh, in your /var/bin/ folder
- "filebot -script fn:configure" if you need subtitles
- If you have java memory errors like me, edit filebot.sh and add "-Xmx1024m" on the last line. It starts with "java -Dunixfs=false...", insert like this "java -Xmx1024m -Dunixfs=false...".

It should work. What a mess!

**Comment by rednoah** [comment]
So you can't install the `oracle-java` package at all? That doesn't make sense. The package might fail to install java, but DSM will most certainly not fail to install the package.

**Comment by remouk** [comment]
"The package might fail to install java, but DSM will most certainly not fail to install the package."
Not sure what the difference is. But I can tell you that in the package repository, only the "Install" button appears on the package, and when I go "inside" the package for more info, there's no "View Log", just like a package that is not installed.

**Comment by rednoah** [comment]
`DS213air` has a `armv5tel` CPU so this package won't work:
https://www.synology.com/en-us/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have

The package will be installed, but the log will say `Unkown CPU architecture: armv5tel`:
https://github.com/rednoah/java-installer/blob/master/src/install-jdk.sh#L25

**Comment by remouk** [comment]
Well that's funny because it's not installed. :D Anyway from what I understand, it would not work even if installed... That's messed up.

Please. Remove this dependency. Keep the "Unofficial Java Installer" in the repository, but as an optional help for those who can use it, instead of blocking people from using Filebot...

**Comment by remouk** [comment]
Sorry, replied to one of your earlier comments BEFORE seeing your edit: "The package might fail to install java, but DSM will most certainly not fail to install the package. Try again, and submit picture proof to proof me wrong. ;)"

So I retried, and this time I had an error (did not appear before): "This package is published by an unknown publisher".

Anyway, I don't care about this install problem anymore, since it will never work on my NAS. :D Just don't make it mandatory, so everyone can enjoy the filebot package.

**Comment by rednoah** [comment]
1.
That depends on your `Trust Level` setting. Synology packages are code-signed and Package Center will only accept the signature of any of my packages if you have added the [public key](https://github.com/rednoah/java-installer/blob/master/package/gpg/FileBot.pub) (either manually, or by adding the [filebot package source](https://app.filebot.net/syno/)). Since `oracle-java` and `filebot` are signed with the same key, you would run into the same issue with both packages.

2.
I will keep the dependency, but I will make it report "everything is shiny" to DSM so that the dependency is always satisfied even if it doesn't work. The `Running` / `Stopped` status screwing with dependencies was unexpected I have to admin.

**Comment by remouk** [comment]
1.
The filebot package source is in my source list, that's how I get the package (no manual download). I guess I'll have to investigate after 2. is resolved. :)

2.
If I understand clearly (english is not my first language sorry), it will appear as mandatory, but if I don't install it I'll be OK? Sounds good to me. What can I follow to be notified when it will be available?

**Comment by rednoah** [comment]
2.
Pretty much, so when the next version of Java is released I'll make a new package, and even though that package won't work for you specifically (and the log will say so) according to DSM it will say `Running`.

**Comment by remouk** [comment]
Sounds really good, and I think I'm not the only one you're gonna help with that change. I'll keep you posted if there's a problem. ;)

Thanks!
