### ISSUE TITLE
not needed anymore

### ISSUE THREAD

**Issue by lordfiSh** [rednoah/java-installer#9]
Synology has there official Java 7 and 8 Plugin, can you fix your Plugin that we don't have to install the "Unofficial Java Installer" if there is always a Java installed? Thanks 

![Screenshot](https://i.imgur.com/TbZl8Sp.png)

**Comment by rednoah** [comment]
Did you do a performance comparison? Oracle JDK was 10x faster on armv7 last time I checked.
